"""remove_sentiment_report_column

Revision ID: 94c47f85a48c
Revises: 002
Create Date: 2025-07-14 13:42:27.188291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c47f85a48c'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'sentiment_report')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('sentiment_report', sa.Text(length=4294967295), nullable=True))
    # ### end Alembic commands ###